apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-selector-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-selector-deployment
  template:
    metadata:
      labels:
        app: node-selector-deployment
    spec:
      containers:
      - name: node-selector-deployment
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80 
      tolerations:
      - key: "nodedown"
        operator: "Equal"
        value: "cpuhigh"
        effect: "NoSchedule"  
      affinity:
        nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: component
                 operator: In
                 values:
                 - msapp
               - key: apptype
                 operator: In
                 values: 
                 - java
                 - common 