apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-selector-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-selector-deployment
  template:
    metadata:
      labels:
        app: node-selector-deployment
    spec:
      containers:
      - name: node-selector-deployment
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
