apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-ingress
  namespace: argocd
  labels:
    name: ingress-service-expose 
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /     
spec:
  ingressClassName: nginx
  rules:          
  - host: argo.mgmt.ocelottraining.com 
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: argocd-argo-cd-server
            port: 
              number: 80 
  