apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp1
    image: nginx:latest
    ports:
      - containerPort: 80
  - name: myapp2
    image: nginx:latest
    ports:
      - containerPort: 8080
