kind: Service
apiVersion: v1
metadata:
  name: mysql-database-service
  labels:
    app: mysql-database
spec:
  selector:
    name: mysql-database
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306