apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-store
provisioner: nfs.csi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
parameters:
  server: 172.31.14.233
  share: /container_data/sharedata

