defaultStorageClass: local-path
adminPassword: admin123
logLevel: debug
ipFamily:
  ipv6:
    enabled: false
  ipv4:
    enabled: true
cache:
  enabled: true
  expireHours: 24    

exposureType: ingress

ingress:
core:
    ingressClassName: nginx
    pathType: ImplementationSpecific
    apiVersion: ""
    controller: default
    hostname: harbor.ocelottraining.com
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    tls: false
    selfSigned: false

persistence:
  enabled: true
  resourcePolicy: ""
  persistentVolumeClaim:
    registry:
      existingClaim: ""
      storageClass: local-path
      subPath: ""
      accessModes:
        - ReadWriteOnce
      size: 2Gi
      annotations: {}
      selector: {}

    jobservice:
      existingClaim: ""
      storageClass: local-path
      subPath: ""
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      annotations: {}
      selector: {}
    trivy:
      storageClass: local-path
      accessModes:
        - ReadWriteOnce
      size: 2Gi
      annotations: {}
      selector: {}

  imageChartStorage:
    caBundleSecret: ""
    disableredirect: false
    type: filesystem
    filesystem:
      rootdirectory: /storage
      maxthreads: ""
    s3:
      region: us-west-1
      bucket: bucketname
      accesskey: ""
      secretkey: ""
      regionendpoint: ""
      encrypt: ""
      keyid: ""
      secure: ""
      skipverify: ""
      v4auth: ""
      chunksize: ""
      rootdirectory: ""
      storageClass: ""
      sse: ""
      multipartcopychunksize: ""
      multipartcopymaxconcurrency: ""
      multipartcopythresholdsize: ""
nginx:
  image:
    registry: docker.io
    repository: bitnami/nginx
    tag: 1.28.0-debian-12-r3
    pullPolicy: IfNotPresent
  tls:
    enabled: false
  behindReverseProxy: false
  containerPorts:
    http: 8080
    https: 8443
  replicaCount: 1
  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 15
    successThreshold: 1
  resourcesPreset: "small"
  resources: {}
  podSecurityContext:
    enabled: false
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
    fsGroup: 1001
  containerSecurityContext:
    enabled: false
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
  updateStrategy:
    type: RollingUpdate
  serviceAccount:
    create: false
   
portal:
  image:
    registry: docker.io
    repository: bitnami/harbor-portal
    tag: 2.13.1-debian-12-r2
  containerPorts:
    http: 8080
    https: 8443
  replicaCount: 1
  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  containerSecurityContext:
    enabled: false     
  networkPolicy:
    enabled: false

core:

  image:
    registry: docker.io
    repository: bitnami/harbor-core
    tag: 2.13.1-debian-12-r7
  
  quotaUpdateProvider: db
  containerPorts:
    http: 8080
    https: 8443
    metrics: 8001  
  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1  
  readinessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  service:
    ports:
      http: 80
      https: 443
      metrics: 8001    
  networkPolicy:
    enabled: false

jobservice:
  image:
    registry: docker.io
    repository: bitnami/harbor-jobservice
    tag: 2.13.1-debian-12-r4  
  containerPorts:
    http: 8080
    https: 8443
    metrics: 8001
  replicaCount: 1      
  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1  
  readinessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  service:
    ports:
      http: 80
      https: 443
      metrics: 8001    
  networkPolicy:
    enabled: false

registry:
  credentials:
    username: harbor_registry_user
    password: harbor_registry_password
    ## If you update the username or password of registry, make sure use cli tool htpasswd to generate the bcrypt hash
    ## e.g. "htpasswd -nbBC10 $username $password"
    ##
    htpasswd: harbor_registry_user:$2y$10$9L4Tc0DJbFFMB6RdSCunrOpTHdwhid4ktBJmLD00bYgqkkGOvll3m     

  uploadPurging:
    enabled: true
    age: 168h
    interval: 24h
    dryrun: false

  server: 
    image:
      registry: docker.io
      repository: bitnami/harbor-registry
      tag: 2.13.1-debian-12-r2    

  controller: 
    image:
      registry: docker.io
      repository: bitnami/harbor-registryctl
      tag: 2.13.1-debian-12-r4    

trivy: 
  image:
    registry: docker.io
    repository: bitnami/harbor-adapter-trivy
    tag: 2.13.1-debian-12-r2
  insecure: true

exporter: 
  image:
    registry: docker.io
    repository: bitnami/harbor-exporter
    tag: 2.13.1-debian-12-r5    


postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: not-secure-database-password
    existingSecret: ""
  architecture: standalone
  primary:
    extendedConfiguration: |
      max_connections = 1024
    initdb:
      scripts:
        initial-registry.sql: |
          CREATE DATABASE registry ENCODING 'UTF8';
          \c registry;
          CREATE TABLE schema_migrations(version bigint not null primary key, dirty boolean not null);

redis:
  enabled: true          