apiVersion: v1
kind: PersistentVolume
metadata:
  name: learning-pv
  labels:
    app: learning-pv-app
spec: 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
     path: "/mnt/learning-pv"
     type: DirectoryOrCreate