apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: all-pod-reader 
rules:
- apiGroups: ["", "apps" ] 
  resources: ["pods", "deployment", "service", "replicasets" ]
  verbs: ["get", "watch", "list"]

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all-pod-reader-bind
subjects:
- kind: User
  name: kube1user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: all-pod-reader
  apiGroup: rbac.authorization.k8s.io