apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-database-pvc-data0
  labels: 
    app: mysql-database
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
