apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-database-persistent-vol
  label:
    app: mysql-database
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /container_data/mysql_data
    server: 172.31.14.233
