kind: Service
apiVersion: v1
metadata:
  name: mysql-database-service
  labels:
    app: mysql-database
spec:
  selector:
    app: mysql-database
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30006   # NodePort is set to 30006, you can change it if needed