apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-server-data0
  labels:
    app: mongo-server-db
spec:
  resources:
    requests:
      storage: "1Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: central-store-fs
